This is a project to compile a pretty comprehensive set of notes and examples on using density functional theory to model properties of materials.

Check out the new blog at http://jkitchin.github.com/dft-book.

* Some notes on dft-book
The book is released under the [[http://www.gnu.org/copyleft/fdl.html][GNU Free Documentation License]]. You are free to copy it, modify it, and redistribute it under the conditions of that license. The book is written in [[http://orgmode.org][org-mode]], and is best read in Emacs. You will be asked by Emacs if it is ok to set some local variables, and load the file dft.el. You should say yes, as that file provides functions needed to read dft.org with all its functionality which includes interactive code examples and links to documentation. dft.org is always up to date. Alternatively, you may prefer the [[https://github.com/jkitchin/dft-book/raw/master/dft.pdf][pdf]] version of the book which is nicely rendered and usually up to date. The mobi version is highly experimental, and usually not up to date.

You are welcome to contribute examples of how to run calculations.

Bug/typo/error reports should be sent to:

John Kitchin (jkitchin@andrew.cmu.edu) or reported as an [[https://github.com/jkitchin/dft-book/issues][issue]].
